customhost = "employee.cmwotwdiwatz.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chowkinleong-employee"
customregion = "us-east-1"
